### ISSUE TITLE
"message" is not allowed (on clean Gatsby v5.5.0 repo)

### ISSUE THREAD

**Issue by mitchuman** [storyblok/gatsby-source-storyblok#182]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

On a clean install of Gatsby v5.5.0 and only the `gatsby-source-storyblok` plugin installed, I get a console error saying `"message" is not allowed`.

No pages are setup, just added in `gatsby-config.js` and the issue occurs.

---

## Expected Behavior

At least have the local server and the GraphQL server up and running.

## Current Behavior

Only addition to `gatsby-config.js` is the following:

```js
{
	resolve: 'gatsby-source-storyblok',
	options: {
		accessToken: '...',
		version: 'draft',
		localAssets: true, // Optional parameter to download the images to use with Gatsby Image Plugin
		// languages: ['en'] // Optional parameter. Omission will retrieve all languages by default.
	}
},
```

Output:
```sh
$ gatsby develop
success compile gatsby files - 0.422s
success load gatsby config - 0.036s
warn Plugin gatsby-source-storyblok is not compatible with your gatsby version 5.5.0 - It requires gatsby@^3.0.0 || ^4.0.0
warn Plugin gatsby-source-storyblok is not compatible with your gatsby version 5.5.0 - It requires gatsby@^3.0.0 || ^4.0.0
success load plugins - 0.408s
success onPreInit - 0.010s
success initialize cache - 0.158s
success copy gatsby files - 0.190s
success Compiling Gatsby Functions - 0.275s
success onPreBootstrap - 0.299s
success createSchemaCustomization - 0.011s
Failed to validate error [Error [ValidationError]: "message" is not allowed] {
  _original: {
    context: {},
    message: Error: Unauthorized
        at /.../node_modules/@storyblok/react/dist/storyblok-react.js:1:7660
        at new Promise (<anonymous>)
        at dt._statusHandler (/.../node_modules/@storyblok/react/dist/storyblok-react.js:1:7586)
        at dt._methodHandler (/.../node_modules/@storyblok/react/dist/storyblok-react.js:1:7472)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at /.../node_modules/@storyblok/react/dist/storyblok-react.js:1:12891,
    response: {
      data: [Object],
      headers: [Object],
      status: 401,
      statusText: 'Unauthorized'
    },
    text: 'There was an unhandled error and we could not retrieve more information. Please run the command with the --verbose flag again.',
    level: 'ERROR',
    category: 'UNKNOWN',
    type: 'UNKNOWN',
    stack: [],
    docsUrl: 'https://gatsby.dev/issue-how-to'
  },
  details: [
    {
      message: '"message" is not allowed',
      path: [Array],
      type: 'object.unknown',
      context: [Object]
    }
  ]
}
not finished source and transform nodes - 0.529s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to Reproduce

`package.json`
```json
"dependencies": {
    "gatsby": "^5.5.0",
    "gatsby-plugin-image": "^3.5.0",
    "gatsby-plugin-sharp": "^5.5.0",
    "gatsby-plugin-sitemap": "^6.5.0",
    "gatsby-source-filesystem": "^5.5.0",
    "gatsby-source-storyblok": "^5.0.0",
    "gatsby-transformer-sharp": "^5.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
```

1. Setup clean Gatsby v.5.5.0
2. Install `gatsby-source-stroyblok`
3. Add `gatsby-config.js` settings
4. Run `yarn develop` or `npm run develop`
5. Error

**Comment by jclark-vanish** [comment]
Similar issue with Gatsby.  Looks like it is not ready for Gatsby 5?
